name: my workflow 
on: push 

jobs: 
  my-first-job: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "hello there"
  my-second-job: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "hi there"